2022-07-02 23:21:16 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration spotify-playlist-sensor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-02 23:21:16 ERROR (SyncWorker_0) [homeassistant.loader] The custom integration 'spotify-playlist-sensor' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
2022-07-02 23:21:16 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration lovelace_gen which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-02 23:21:16 ERROR (SyncWorker_1) [homeassistant.loader] The custom integration 'lovelace_gen' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
2022-07-02 23:21:16 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration amazon_rekognition which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-02 23:21:16 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration start_time which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-02 23:21:16 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration braviatv_psk which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-02 23:21:16 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration car_wash which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-02 23:21:16 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration tahoma which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-02 23:21:16 WARNING (SyncWorker_8) [homeassistant.loader] We found a custom integration spotcast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-02 23:21:16 WARNING (SyncWorker_7) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-02 23:21:16 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-02 23:21:16 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nuki_ng which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-02 23:21:16 WARNING (SyncWorker_9) [homeassistant.loader] We found a custom integration powercalc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-02 23:21:16 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration aquaariston which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-02 23:21:16 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-02 23:21:16 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2022-07-02 23:21:17 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=819 from 2022-06-29 23:01:41.220506)
2022-07-02 23:21:20 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-02 23:21:32 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom component author for powercalc using this method at custom_components/powercalc/__init__.py, line 176: entity_registry = await er.async_get_registry(hass)
2022-07-02 23:21:32 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for powercalc using this method at custom_components/powercalc/model_discovery.py, line 106: device_registry = await dr.async_get_registry(hass)
2022-07-02 23:21:32 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for powercalc using this method at custom_components/powercalc/model_discovery.py, line 73: device_registry = await dr.async_get_registry(hass)
2022-07-02 23:21:32 ERROR (MainThread) [homeassistant.components.sensor] Platform esphome does not generate unique IDs. ID dallas-0000000000000000 already exists - ignoring sensor.q1_quinled_deca_temp
2022-07-02 23:21:32 ERROR (MainThread) [homeassistant.components.light] Platform esphome does not generate unique IDs. ID livingroom_ceiling_led_1lightlivingroom_ceiling_led_1 already exists - ignoring light.livingroom_ceiling_led_1
2022-07-02 23:21:32 ERROR (MainThread) [homeassistant.components.light] Platform esphome does not generate unique IDs. ID livingroom_ceiling_led_1lightq1_quinled_deca-2 already exists - ignoring light.q1_quinled_deca_2
2022-07-02 23:21:32 ERROR (MainThread) [homeassistant.components.light] Platform esphome does not generate unique IDs. ID livingroom_ceiling_led_1lightq1_quinled_deca-3 already exists - ignoring light.q1_quinled_deca_3
2022-07-02 23:21:32 ERROR (MainThread) [homeassistant.components.light] Platform esphome does not generate unique IDs. ID livingroom_ceiling_led_1lightq1_quinled_deca-4 already exists - ignoring light.q1_quinled_deca_4
2022-07-02 23:21:32 ERROR (MainThread) [homeassistant.components.light] Platform esphome does not generate unique IDs. ID livingroom_ceiling_led_1lightq1_quinled_deca-5 already exists - ignoring light.q1_quinled_deca_5
2022-07-02 23:21:32 ERROR (MainThread) [homeassistant.components.light] Platform esphome does not generate unique IDs. ID livingroom_ceiling_led_1lightq1_quinled_deca-6 already exists - ignoring light.livingroom_deca_6
2022-07-02 23:21:32 ERROR (MainThread) [homeassistant.components.light] Platform esphome does not generate unique IDs. ID livingroom_ceiling_led_1lightq1_quinled_deca-7 already exists - ignoring light.livingroom_deca_7
2022-07-02 23:21:32 ERROR (MainThread) [homeassistant.components.light] Platform esphome does not generate unique IDs. ID livingroom_ceiling_led_1lightq1_quinled_deca-8 already exists - ignoring light.livingroom_deca_8
2022-07-02 23:21:32 ERROR (MainThread) [homeassistant.components.light] Platform esphome does not generate unique IDs. ID livingroom_ceiling_led_1lightq1_quinled_deca-9 already exists - ignoring light.livingroom_deca_9
2022-07-02 23:21:32 ERROR (MainThread) [homeassistant.components.light] Platform esphome does not generate unique IDs. ID livingroom_ceiling_led_1lightlivingroom_ceiling_led_2 already exists - ignoring light.livingroom_ceiling_led_2
2022-07-02 23:21:32 ERROR (MainThread) [custom_components.smartthinq_sensors] Invalid ThinQ credential error, integration setup aborted. Please use the LG App on your mobile device to ensure your credentials are correct, then restart HomeAssistant. If your credential changed, you must reconfigure integration
2022-07-02 23:21:33 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for tahoma using this method at custom_components/tahoma/__init__.py, line 141: device_registry = await dr.async_get_registry(hass)
2022-07-02 23:21:35 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for bedroom_bed_esp @ 192.168.1.27: Error connecting to ('192.168.1.27', 6053): [Errno 113] Connect call failed ('192.168.1.27', 6053)
2022-07-02 23:21:35 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for tagreader @ 192.168.1.187: Error connecting to ('192.168.1.187', 6053): [Errno 113] Connect call failed ('192.168.1.187', 6053)
2022-07-02 23:21:42 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Hallway WLED' for wled integration not ready yet: Invalid response from API: Timeout occurred while connecting to WLED device at 192.168.1.82; Retrying in background
2022-07-02 23:21:45 WARNING (MainThread) [homeassistant.components.automation.toggle_the_main_light_based_on_door_sensor] Toggle the main light based on door sensor: Already running
2022-07-02 23:21:56 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 220, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/image/__init__.py", line 194, in get
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/image/__init__.py", line 210, in _generate_thumbnail
    image = ImageOps.exif_transpose(Image.open(original_path))
  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 3068, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/config/image/b46152742f1a261655cb02d8e9e671e5/original'
2022-07-02 23:22:05 WARNING (MainThread) [homeassistant.components.automation.office_wardrobe_lights_by_door_sensors] Office Wardrobe Lights By Door sensors: Already running
2022-07-02 23:22:05 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Office Closet Lights Toggle By Door: If at step 1: Error executing script. Service not found for call_service at pos 1: Unable to find service light.turn_unavailable
2022-07-02 23:22:05 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Office Closet Lights Toggle By Door: If at step 1: Error executing script. Service not found for call_service at pos 1: Unable to find service light.turn_unavailable
2022-07-02 23:22:05 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Office Closet Lights Toggle By Door: If at step 1: Error executing script. Service not found for call_service at pos 1: Unable to find service light.turn_unavailable
2022-07-02 23:22:05 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Office Closet Lights Toggle By Door: If at step 1: Error executing script. Service not found for call_service at pos 1: Unable to find service light.turn_unavailable
2022-07-02 23:22:05 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Office Closet Lights Toggle By Door: Error executing script. Service not found for if at pos 1: Unable to find service light.turn_unavailable
2022-07-02 23:22:05 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Office Closet Lights Toggle By Door: Error executing script. Service not found for if at pos 1: Unable to find service light.turn_unavailable
2022-07-02 23:22:05 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Office Closet Lights Toggle By Door: Error executing script. Service not found for if at pos 1: Unable to find service light.turn_unavailable
2022-07-02 23:22:05 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Office Closet Lights Toggle By Door: Error executing script. Service not found for if at pos 1: Unable to find service light.turn_unavailable
2022-07-02 23:22:05 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Error while executing automation automation.office_closet_lights_toggle_by_door: Unable to find service light.turn_unavailable
2022-07-02 23:22:05 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Error while executing automation automation.office_closet_lights_toggle_by_door: Unable to find service light.turn_unavailable
2022-07-02 23:22:05 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Error while executing automation automation.office_closet_lights_toggle_by_door: Unable to find service light.turn_unavailable
2022-07-02 23:22:05 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Error while executing automation automation.office_closet_lights_toggle_by_door: Unable to find service light.turn_unavailable
2022-07-02 23:22:10 WARNING (MainThread) [homeassistant.components.automation.office_wardrobe_lights_by_door_sensors] Office Wardrobe Lights By Door sensors: Already running
2022-07-02 23:22:10 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Office Closet Lights Toggle By Door: If at step 1: Error executing script. Service not found for call_service at pos 1: Unable to find service light.turn_unknown
2022-07-02 23:22:10 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Office Closet Lights Toggle By Door: If at step 1: Error executing script. Service not found for call_service at pos 1: Unable to find service light.turn_unknown
2022-07-02 23:22:10 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Office Closet Lights Toggle By Door: If at step 1: Error executing script. Service not found for call_service at pos 1: Unable to find service light.turn_unknown
2022-07-02 23:22:10 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Office Closet Lights Toggle By Door: If at step 1: Error executing script. Service not found for call_service at pos 1: Unable to find service light.turn_unknown
2022-07-02 23:22:10 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Office Closet Lights Toggle By Door: Error executing script. Service not found for if at pos 1: Unable to find service light.turn_unknown
2022-07-02 23:22:10 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Office Closet Lights Toggle By Door: Error executing script. Service not found for if at pos 1: Unable to find service light.turn_unknown
2022-07-02 23:22:10 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Office Closet Lights Toggle By Door: Error executing script. Service not found for if at pos 1: Unable to find service light.turn_unknown
2022-07-02 23:22:10 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Office Closet Lights Toggle By Door: Error executing script. Service not found for if at pos 1: Unable to find service light.turn_unknown
2022-07-02 23:22:10 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Error while executing automation automation.office_closet_lights_toggle_by_door: Unable to find service light.turn_unknown
2022-07-02 23:22:10 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Error while executing automation automation.office_closet_lights_toggle_by_door: Unable to find service light.turn_unknown
2022-07-02 23:22:10 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Error while executing automation automation.office_closet_lights_toggle_by_door: Unable to find service light.turn_unknown
2022-07-02 23:22:10 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Error while executing automation automation.office_closet_lights_toggle_by_door: Unable to find service light.turn_unknown
2022-07-02 23:22:10 WARNING (MainThread) [homeassistant.components.automation.office_wardrobe_lights_by_door_sensors] Office Wardrobe Lights By Door sensors: Already running
2022-07-02 23:22:10 WARNING (MainThread) [homeassistant.components.automation.kitchen_water_leak_warning] Kitchen Water Leak Warning: Already running
2022-07-02 23:22:11 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Office Closet Lights Toggle By Door: If at step 1: Error executing script. Service not found for call_service at pos 1: Unable to find service light.turn_unknown
2022-07-02 23:22:11 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Office Closet Lights Toggle By Door: If at step 1: Error executing script. Service not found for call_service at pos 1: Unable to find service light.turn_unknown
2022-07-02 23:22:11 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Office Closet Lights Toggle By Door: Error executing script. Service not found for if at pos 1: Unable to find service light.turn_unknown
2022-07-02 23:22:11 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Office Closet Lights Toggle By Door: Error executing script. Service not found for if at pos 1: Unable to find service light.turn_unknown
2022-07-02 23:22:11 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Error while executing automation automation.office_closet_lights_toggle_by_door: Unable to find service light.turn_unknown
2022-07-02 23:22:11 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Error while executing automation automation.office_closet_lights_toggle_by_door: Unable to find service light.turn_unknown
2022-07-02 23:22:11 WARNING (MainThread) [homeassistant.components.automation.office_wardrobe_lights_by_door_sensors] Office Wardrobe Lights By Door sensors: Already running
2022-07-02 23:22:11 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Office Closet Lights Toggle By Door: If at step 1: Error executing script. Service not found for call_service at pos 1: Unable to find service light.turn_unknown
2022-07-02 23:22:11 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Office Closet Lights Toggle By Door: If at step 1: Error executing script. Service not found for call_service at pos 1: Unable to find service light.turn_unknown
2022-07-02 23:22:11 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Office Closet Lights Toggle By Door: Error executing script. Service not found for if at pos 1: Unable to find service light.turn_unknown
2022-07-02 23:22:11 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Office Closet Lights Toggle By Door: Error executing script. Service not found for if at pos 1: Unable to find service light.turn_unknown
2022-07-02 23:22:11 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Error while executing automation automation.office_closet_lights_toggle_by_door: Unable to find service light.turn_unknown
2022-07-02 23:22:11 ERROR (MainThread) [homeassistant.components.automation.office_closet_lights_toggle_by_door] Error while executing automation automation.office_closet_lights_toggle_by_door: Unable to find service light.turn_unknown
2022-07-02 23:26:43 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.bedroom_wardrobe_pre_trafo, switch.kitchen_pre_trafo_working_desk_light, switch.kitchen_stove, switch.living_room_below_tv_led_pre_trafo, switch.office_pre_trafo_wardrobe or it is/they are currently not available
2022-07-02 23:27:48 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities scene.warning_lights or it is/they are currently not available
2022-07-02 23:27:48 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities scene.all_lights or it is/they are currently not available
2022-07-02 23:30:25 WARNING (Thread-154) [custom_components.aquaariston.aristonaqua] <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x146cc6ed3940> _get_time_prog Problem reading data
2022-07-02 23:30:25 WARNING (Thread-154) [custom_components.aquaariston.aristonaqua] ariston action nok for _get_time_prog: Request _get_time_prog has failed with an exception
2022-07-02 23:51:40 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 220, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/image/__init__.py", line 194, in get
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/image/__init__.py", line 210, in _generate_thumbnail
    image = ImageOps.exif_transpose(Image.open(original_path))
  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 3068, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/config/image/b46152742f1a261655cb02d8e9e671e5/original'
2022-07-03 00:00:00 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities light.bedroom_wall_wled or it is/they are currently not available
2022-07-03 00:13:06 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'source' is undefined when rendering '{{ source }}'
2022-07-03 00:13:06 ERROR (MainThread) [homeassistant.components.denonavr.media_player] Command async_select_source failed with error: No mapping for input source 
2022-07-03 00:17:58 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities scene.warning_lights or it is/they are currently not available
2022-07-03 00:17:58 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities scene.all_lights or it is/they are currently not available
2022-07-03 01:08:07 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities scene.warning_lights or it is/they are currently not available
2022-07-03 01:08:07 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities scene.all_lights or it is/they are currently not available
2022-07-03 01:58:21 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities scene.warning_lights or it is/they are currently not available
2022-07-03 01:58:21 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities scene.all_lights or it is/they are currently not available
2022-07-03 02:06:24 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 220, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/image/__init__.py", line 194, in get
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/image/__init__.py", line 210, in _generate_thumbnail
    image = ImageOps.exif_transpose(Image.open(original_path))
  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 3068, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/config/image/b46152742f1a261655cb02d8e9e671e5/original'
2022-07-03 02:07:55 WARNING (Thread-1067) [custom_components.aquaariston.aristonaqua] <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x146cc6ed3940> _get_cleanse Problem reading data
2022-07-03 02:07:55 WARNING (Thread-1067) [custom_components.aquaariston.aristonaqua] ariston action nok for _get_cleanse: Request _get_cleanse has failed with an exception
2022-07-03 02:08:19 WARNING (Thread-1069) [custom_components.aquaariston.aristonaqua] <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x146cc6ed3940> _get_error Problem reading data
2022-07-03 02:08:19 WARNING (Thread-1069) [custom_components.aquaariston.aristonaqua] ariston action nok for _get_error: Request _get_error has failed with an exception
2022-07-03 02:08:49 WARNING (Thread-1071) [custom_components.aquaariston.aristonaqua] <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x146cc6ed3940> _get_time_prog Problem reading data
2022-07-03 02:08:49 WARNING (Thread-1071) [custom_components.aquaariston.aristonaqua] ariston action nok for _get_time_prog: Request _get_time_prog has failed with an exception
2022-07-03 02:09:37 WARNING (Thread-1074) [custom_components.aquaariston.aristonaqua] <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x146cc6ed3940> _get_main Problem reading data
2022-07-03 02:09:37 WARNING (Thread-1074) [custom_components.aquaariston.aristonaqua] Connection errors: 1
2022-07-03 02:09:37 WARNING (Thread-1074) [custom_components.aquaariston.aristonaqua] ariston action nok for _get_main: Request _get_main has failed with an exception
2022-07-03 02:10:01 WARNING (Thread-1076) [custom_components.aquaariston.aristonaqua] <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x146cc6ed3940> _get_main Problem reading data
2022-07-03 02:10:01 WARNING (Thread-1076) [custom_components.aquaariston.aristonaqua] Connection errors: 2
2022-07-03 02:10:01 WARNING (Thread-1076) [custom_components.aquaariston.aristonaqua] ariston action nok for _get_main: Request _get_main has failed with an exception
2022-07-03 02:10:25 WARNING (Thread-1078) [custom_components.aquaariston.aristonaqua] <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x146cc6ed3940> _get_main Problem reading data
2022-07-03 02:10:25 WARNING (Thread-1078) [custom_components.aquaariston.aristonaqua] Connection errors: 3
2022-07-03 02:10:25 WARNING (Thread-1078) [custom_components.aquaariston.aristonaqua] ariston action nok for _get_main: Request _get_main has failed with an exception
2022-07-03 02:10:49 WARNING (Thread-1080) [custom_components.aquaariston.aristonaqua] <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x146cc6ed3940> _get_main Problem reading data
2022-07-03 02:10:49 WARNING (Thread-1080) [custom_components.aquaariston.aristonaqua] Connection errors: 4
2022-07-03 02:10:49 WARNING (Thread-1080) [custom_components.aquaariston.aristonaqua] ariston action nok for _get_main: Request _get_main has failed with an exception
2022-07-03 02:11:13 WARNING (Thread-1082) [custom_components.aquaariston.aristonaqua] <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x146cc6ed3940> _get_main Problem reading data
2022-07-03 02:11:13 WARNING (Thread-1082) [custom_components.aquaariston.aristonaqua] Connection errors: 5
2022-07-03 02:11:13 WARNING (Thread-1082) [custom_components.aquaariston.aristonaqua] ariston action nok for _get_main: Request _get_main has failed with an exception
2022-07-03 02:11:37 WARNING (Thread-1084) [custom_components.aquaariston.aristonaqua] <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x146cc6ed3940> _get_main Problem reading data
2022-07-03 02:11:37 WARNING (Thread-1084) [custom_components.aquaariston.aristonaqua] Connection errors: 6
2022-07-03 02:11:37 WARNING (Thread-1084) [custom_components.aquaariston.aristonaqua] ariston action nok for _get_main: Request _get_main has failed with an exception
2022-07-03 02:12:01 WARNING (Thread-1086) [custom_components.aquaariston.aristonaqua] <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x146cc6ed3940> _get_main Problem reading data
2022-07-03 02:12:01 WARNING (Thread-1086) [custom_components.aquaariston.aristonaqua] Connection errors: 7
2022-07-03 02:12:01 WARNING (Thread-1086) [custom_components.aquaariston.aristonaqua] ariston action nok for _get_main: Request _get_main has failed with an exception
2022-07-03 02:12:06 WARNING (Thread-1085) [custom_components.aquaariston.aristonaqua] <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x146cc6ed3940> Retrying in 72.0 seconds
2022-07-03 02:12:26 WARNING (Thread-1088) [custom_components.aquaariston.aristonaqua] <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x146cc6ed3940> _get_main Problem reading data
2022-07-03 02:12:26 WARNING (Thread-1088) [custom_components.aquaariston.aristonaqua] Connection errors: 8
2022-07-03 02:12:26 WARNING (Thread-1088) [custom_components.aquaariston.aristonaqua] ariston action nok for _get_main: Request _get_main has failed with an exception
2022-07-03 02:13:18 WARNING (Thread-1087) [custom_components.aquaariston.aristonaqua] <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x146cc6ed3940> Retrying in 72.0 seconds
2022-07-03 02:13:37 WARNING (Thread-1090) [custom_components.aquaariston.aristonaqua] <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x146cc6ed3940> _get_main Problem reading data
2022-07-03 02:13:37 WARNING (Thread-1090) [custom_components.aquaariston.aristonaqua] Connection errors: 9
2022-07-03 02:13:37 WARNING (Thread-1090) [custom_components.aquaariston.aristonaqua] ariston action nok for _get_main: Request _get_main has failed with an exception
2022-07-03 02:14:20 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 220, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/image/__init__.py", line 194, in get
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/image/__init__.py", line 210, in _generate_thumbnail
    image = ImageOps.exif_transpose(Image.open(original_path))
  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 3068, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/config/image/b46152742f1a261655cb02d8e9e671e5/original'
2022-07-03 02:14:30 WARNING (Thread-1089) [custom_components.aquaariston.aristonaqua] <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x146cc6ed3940> Retrying in 72.0 seconds
2022-07-03 02:14:49 WARNING (Thread-1092) [custom_components.aquaariston.aristonaqua] <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x146cc6ed3940> _get_main Problem reading data
2022-07-03 02:14:49 WARNING (Thread-1092) [custom_components.aquaariston.aristonaqua] Connection errors: 10
2022-07-03 02:14:49 WARNING (Thread-1092) [custom_components.aquaariston.aristonaqua] ariston action nok for _get_main: Request _get_main has failed with an exception
2022-07-03 02:15:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:15:42 WARNING (Thread-1091) [custom_components.aquaariston.aristonaqua] <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x146cc6ed3940> Retrying in 72.0 seconds
2022-07-03 02:16:01 WARNING (Thread-1094) [custom_components.aquaariston.aristonaqua] <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x146cc6ed3940> _get_main Problem reading data
2022-07-03 02:16:01 WARNING (Thread-1094) [custom_components.aquaariston.aristonaqua] Connection errors: 11
2022-07-03 02:16:01 ERROR (Thread-1094) [custom_components.aquaariston.aristonaqua] Ariston is offline: Too many errors
2022-07-03 02:16:01 WARNING (Thread-1094) [custom_components.aquaariston.aristonaqua] ariston action nok for _get_main: Request _get_main has failed with an exception
2022-07-03 02:16:03 WARNING (MainThread) [homeassistant.helpers.script] Error in 'choose[0]' evaluation: In 'template' condition: ValueError: Template error: int got invalid input 'unavailable' when rendering template '{{ states('sensor.aqua_ariston_current_temperature') | int < 50}}' but no default was specified
2022-07-03 02:16:03 WARNING (MainThread) [homeassistant.helpers.script] Error in 'choose[0]' evaluation: In 'template' condition: ValueError: Template error: int got invalid input 'unavailable' when rendering template '{{ states('sensor.aqua_ariston_current_temperature') | int > 65}}' but no default was specified
2022-07-03 02:16:05 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:16:05 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:16:34 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:16:34 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:16:34 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:16:34 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:16:34 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:16:35 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:16:35 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:16:54 WARNING (Thread-1093) [custom_components.aquaariston.aristonaqua] <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x146cc6ed3940> Retrying in 72.0 seconds
2022-07-03 02:17:00 WARNING (Thread-1096) [custom_components.aquaariston.aristonaqua] <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x146cc6ed3940> Authentication login error
2022-07-03 02:17:00 WARNING (Thread-1096) [custom_components.aquaariston.aristonaqua] Connection errors: 12
2022-07-03 02:17:00 WARNING (Thread-1096) [custom_components.aquaariston.aristonaqua] ariston action nok for _get_main: Login request exception
2022-07-03 02:17:53 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:17:53 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:17:53 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:17:53 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:17:53 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:17:53 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:17:53 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:17:53 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:18:06 WARNING (Thread-1095) [custom_components.aquaariston.aristonaqua] <custom_components.aquaariston.aristonaqua.AquaAristonHandler object at 0x146cc6ed3940> Retrying in 72.0 seconds
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:19:23 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:22 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:20:46 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:50 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:21:55 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:22:03 ERROR (MainThread) [homeassistant.config] Invalid config for [script]: required key not provided @ data['sequence']. Got None. (See /config/configuration.yaml, line 59). 
2022-07-03 02:32:28 WARNING (MainThread) [homeassistant.components.automation.kitchen_extraction_fan_toggle_by_kitchen_stove] Kitchen extraction fan toggle by kitchen stove: Already running
